### ISSUE TITLE
[BUG] M2 directory creation overwrites the existing /root/.m2 path which now has a custom maven plugin we need

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/kantra#117] opened 2023-11-08 22:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

latest

### Priority

Blocker

### Current Behavior

Dependency sources downloads fail because the directory where we keep our maven plugin gets overwritten due to  https://github.com/konveyor/kantra/pull/105 

There is a custom maven plugin we introduced in https://github.com/konveyor/java-analyzer-bundle/pull/81 This plugin is required to run the sources download correctly.

### Expected Behavior

The stuff under existing m2 directory should not get overwritten and sources downloads should not result in error.

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Run analysis against tackle-testapp with target cloud-readiness
2. Notice that the issue for `local-storage-00001` rule is not present in the report.

### Environment

```markdown
- OS: Linux
```

**Comment by ascheman** [comment] 2023-11-09 07:06
I am not sure if it works with multiple local repositories, but you could try to add a second local repository in the `settings.xml` file, cf. https://maven.apache.org/guides/mini/guide-multiple-repositories.html.

**Comment by ascheman** [comment] 2023-11-09 12:32
Stay tuned, the root cause of the Maven plugin, which required a custom solution, is [addressed at the Maven project](https://issues.apache.org/jira/browse/MDEP-895), and @jmle already provided [a bugfix and PR](https://github.com/apache/maven-dependency-plugin/pull/349) which is currently under review.

**Comment by jmle** [comment] 2023-11-09 12:50
> I am not sure if it works with multiple local repositories, but you could try to add a second local repository in the `settings.xml` file, cf. https://maven.apache.org/guides/mini/guide-multiple-repositories.html.

According to ChatGPT it is possible, just need to specify a path in the `<url>` field. We can either change the shared `.m2` or the one coming from the bundle. What do you think?

**Comment by ascheman** [comment] 2023-11-09 13:57
I understand, the shared `.m2` is the problem as it is overridden by the Docker volume mount during runtime. Hence, there should be an additional repo somewhere in the container with your custom plugin.

**Comment by jmle** [comment] 2023-11-09 14:29
Looks like ChatGPT was wrong on this one!

**Comment by ascheman** [comment] 2023-11-13 09:41
Thanks to the merge of https://github.com/apache/maven-dependency-plugin/pull/349 by @slawekjaranowski
the latest SNAPSHOT should now be available in https://repository.apache.org/content/groups/snapshots/org/apache/maven/plugins/maven-dependency-plugin/3.6.2-SNAPSHOT/. So you could try to use this one now as (additional) plugin-repository, @jmle.

**Comment by jmle** [comment] 2023-11-15 14:55
If everything goes fine with https://github.com/konveyor/analyzer-lsp/pull/426 we will be able to close this one.

**Closed** 2023-11-15 18:56 UTC
Labels: kind/bug, priority/release-blocker
